INSERT INTO USERS ("ID", "EMAIL", "FIRST_NAME", "LAST_NAME", "PASSWORD", "ROLE") VALUES (1, 'user', 'user', 'user', '5f4dcc3b5aa765d61d8327deb882cf99', 1);

 INSERT INTO PRODUCT("ID","ACTIVE","CREATOR","DESCRIPTION","PRICE","PRODUCT_CODE", "CREATION_DATE")
 VALUES(1,'true',1,'This item was created at the very last moment',214,12, '2019-05-17') ;

  INSERT INTO PRODUCT("ID","ACTIVE","CREATOR","DESCRIPTION","PRICE","PRODUCT_CODE", "CREATION_DATE")
 VALUES(2,'false',1,'Inactive item',14,212, '2019-05-17') ;

 /*INSERT INTO PRICE_REDUCTION(ID, END_DATE, START_DATE) VALUES (10, '2019-10-26', '2019-10-22');


 INSERT INTO PRODUCT_PRICE_REDUCTION_LIST(PRODUCT_ID, PRICE_REDUCTION_LIST_ID) VALUES (1, 10);

 INSERT INTO SUPPLIERS(ID, COUNTRY, NAME) VALUES (20, 'Spain', 'SuperEmpresa');

 INSERT INTO PRODUCT_SUPPLIER_LIST (PRODUCT_ID , SUPPLIER_LIST_ID ) VALUES (1, 20); */